class Geometry:
    def __init__(self: Geometry, vertices: list[float] = None, uvs: list[float]
                 = None, normals: list[float] = None) -> None: ...

    def set_normals(self: Geometry, normals: list[float]) -> None: ...
    def set_vertices(self: Geometry, vertices: list[float]) -> None: ...
    def set_uvs(self: Geometry, uvs: list[float]) -> None: ...

    def get_normals(self: Geometry) -> list[float]: ...
    def get_vertices(self: Geometry) -> list[float]: ...
    def get_uvs(self: Geometry) -> list[float]: ...

    def get_normals_as_bytes(self: Geometry) -> bytes: ...
    def get_vertices_as_bytes(self: Geometry) -> bytes: ...
    def get_uvs_as_bytes(self: Geometry) -> bytes: ...
