# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'menu.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1061, 781)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.SettingsButton = QtWidgets.QPushButton(self.centralwidget)
        self.SettingsButton.setGeometry(QtCore.QRect(340, 340, 411, 71))
        self.SettingsButton.setObjectName("SettingsButton")
        self.OnlineConnectionButton = QtWidgets.QPushButton(self.centralwidget)
        self.OnlineConnectionButton.setGeometry(QtCore.QRect(340, 190, 411, 71))
        self.OnlineConnectionButton.setObjectName("OnlineConnectionButton")
        self.ExitButton = QtWidgets.QPushButton(self.centralwidget)
        self.ExitButton.setGeometry(QtCore.QRect(340, 480, 411, 71))
        self.ExitButton.setObjectName("ExitButton")
        self.VolumeButton = QtWidgets.QPushButton(self.centralwidget)
        self.VolumeButton.setGeometry(QtCore.QRect(410, 180, 291, 81))
        self.VolumeButton.setObjectName("VolumeButton")
        self.SizeButton = QtWidgets.QPushButton(self.centralwidget)
        self.SizeButton.setGeometry(QtCore.QRect(410, 330, 291, 81))
        self.SizeButton.setObjectName("SizeButton")
        self.ToMenuButton = QtWidgets.QPushButton(self.centralwidget)
        self.ToMenuButton.setGeometry(QtCore.QRect(20, 680, 151, 41))
        self.ToMenuButton.setObjectName("ToMenuButton")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1061, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.SettingsButton.setText(_translate("MainWindow", "Настройки"))
        self.OnlineConnectionButton.setText(_translate("MainWindow", "Сетевая игра"))
        self.ExitButton.setText(_translate("MainWindow", "Выйти из игры"))
        self.VolumeButton.setText(_translate("MainWindow", "Громкость"))
        self.SizeButton.setText(_translate("MainWindow", "Размер окна"))
        self.ToMenuButton.setText(_translate("MainWindow", "Назад"))
